### PR TITLE
Consistent simplified conditionals

### PR DESCRIPTION
**Pull request by arilivigni**
- fixed all when statements for compound conditionals
- fixed project_repo to point to contra-env-infra
- only load containers from samples directory when setup_sample_project=true
- issues with container-tools so blacklist for now
  - it loads as contra-env-infra and fedora instead of container-tools and fails

### CODE REVIEW

**Comment by arilivigni** [comment]
[test]

**Comment by skatlapa** [comment]
[test]

**Comment by arilivigni** [comment]
[test]

**Comment by arilivigni** [comment]
[test]

**Comment by dirgim** [comment]
[test]

**Pull request merged**
