### PR TITLE
Clean out extra cruft after the url for the openshift tarball

### PR DESCRIPTION
**Pull request by herlo**
When using the current code to download the openshift binary, I was getting the following result, causing an error.

```
$ curl -s https://github.com/openshift/origin/releases/v3.9.0 | grep 'openshift-origin-client-tools-.*-linux.*.tar.gz' | head -1 | sed 's/.*<a href="\(.*\)" .*/https:\/\/github.com\1/'

https://github.com/openshift/origin/releases/download/v3.9.0/openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz" rel="nofollow
```
This PR cleans out the extra 'rel=nofollow' bit, ensuring the next task doesn't fail to pull down the openshift binary. If the 'rel=nofollow' bit doesn't show up, the extra sed bit does nothing.

### CODE REVIEW

**Comment by dirgim** [comment]
I think we already covered this in #69 ?

**Comment by dirgim** [comment]
LGTM

**Comment by dirgim** [comment]
Sorry, I deleted my comment, I think we handled this with #69

**Comment by arilivigni** [comment]
#69 addressed it

**Pull request closed without merging**
