### PR TITLE
Use ansible module get_url for getting files

### PR DESCRIPTION
**Pull request by lslebodn**
Ansible module unarchive supports extracting files from URL.
But there is not a way how to increase timeout in case of network
issues. Module get_url has default timeout 10 seconds for URL requests
and it can be changed.
    
https://github.com/ansible/ansible/issues/23864
http://docs.ansible.com/ansible/latest/unarchive_module.html
http://docs.ansible.com/ansible/latest/get_url_module.html
    
    TASK [minishift : Pull down and extract minishift binary to /root] ****
    fatal: [hp-bl465cg8-1.example.com]: FAILED! => {"changed": false,
          "msg": "Failure downloading https://github.com/minishift/minishift/releases/download/v1.12.0/minishift-1.12.0-linux-amd64.tgz,
          ('The read operation timed out',)"}
          to retry, use: --limit @/home/user/projects/contra-env-setup/playbooks/setup.retry

### CODE REVIEW

**Comment by firemanxbr** [comment]
This was different in PR #9:
* Version of Minishift 
* In the Readme exist requirement to install ansible and libselinux
* Get url fixed too

I don't know why we are reviewing the master branch than the latest PR#9

**Comment by lslebodn** [comment]
>This was different in PR #9:
>
>    Version of Minishift
>    In the Readme exist requirement to install ansible and libselinux

1st patch solves it in nicer way because ansible will install it itself :-)

>    Get url fixed too
>

Thank you; I will drop second patch to avoid conflicts with your version.

>I don't know why we are reviewing the master branch than the latest PR#9

I usually prefer to start with master in new project to be sure that it works and new pull request will not break it.
Does it make sense?

**Comment by firemanxbr** [comment]
@lslebodn we can automate the installation of libselinux-python. 
Your approach to start reviewing is right, but we created this project forking this directory of ci-pipeline(https://github.com/CentOS-PaaS-SIG/ci-pipeline/tree/master/dev_setup) with a goal: Create new contra-env-setup to support not only contra team but other teams. I guess this created this miscommunication.

**Comment by firemanxbr** [comment]
@lslebodn I suggest to you create a separated issue just to improve the installation of libselinux-python.

**Pull request closed without merging**
