### PR TITLE
Update minishift & oc download URLs

### PR DESCRIPTION
**Pull request by nmars**
Updated `minishift` & `oc` download base URLs

### CODE REVIEW

**Comment by 14rcole** [comment]
LGTM

**Comment by samvarankashyap** [comment]
lgtm

**Comment by 14rcole** [comment]
@nmars can this be merged?  And should it be merged to the crc branch instead?

**Comment by nmars** [comment]
I think this should be merged to master and then incorporated into crc branch

**Comment by nmars** [comment]
Note, I don't have rights to merge to this repo.

**Pull request merged**
