### PR TITLE
Bump version of OpenShift from 3.9 to 3.10

### PR DESCRIPTION
**Pull request by arilivigni**
* The default is 3.9 but we want to move to 3.10 OpenShift

### CODE REVIEW

**Comment by dirgim** [comment]
[test]

**Comment by dirgim** [comment]
[test]

**Comment by dirgim** [comment]
[test]

**Comment by dirgim** [comment]
test

**Comment by dirgim** [comment]
test

**Comment by dirgim** [comment]
[test]

**Comment by arilivigni** [comment]
@dirgim Can we rerun the CI against this again so it passes?

**Comment by arilivigni** [comment]
[test]

**Comment by dirgim** [comment]
@arilivigni  I think the build failure isn't because of a pipeline problem, the newer minishift version is incompatible with the version flag

**Comment by arilivigni** [comment]
[test]

**Comment by dirgim** [comment]
[test]

**Comment by dirgim** [comment]
[test]

**Pull request merged**
