### PR TITLE
Revert "use github api"

### PR DESCRIPTION
**Pull request by arilivigni**
Reverts CentOS-PaaS-SIG/contra-env-setup#75

Anonymous will use up connections to the github API I believe that is why I used curl to begin with.  With curl there is no limit

### CODE REVIEW

**Comment by arilivigni** [comment]
@psiroky FYI

**Comment by arilivigni** [comment]
[test]

**Comment by dirgim** [comment]
[test]

**Comment by joejstuart** [comment]
Thanks for catching this @psiroky. Looks like there's been a lot of discussion around this in other PR's I hadn't noticed.

**Comment by psiroky** [comment]
Thanks for the fix. @joejstuart no worries, this is something which is not obvious at all. I only learnt about it once I did the same mistake few years back :)

**Pull request merged**
